# Generated by Django 5.2.5 on 2025-08-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamK', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesliderimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homesliderimage',
            name='title',
        ),
        migrations.AddField(
            model_name='homesliderimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images/'),
        ),
        migrations.AddField(
            model_name='homesliderimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homesliderimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images/'),
        ),
    ]
