# Generated by Django 5.2.5 on 2025-08-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamK', '0002_remove_homesliderimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesliderimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
        migrations.AlterField(
            model_name='homesliderimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
        migrations.AlterField(
            model_name='homesliderimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
    ]
