# Generated by Django 5.2.5 on 2025-08-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamK', '0003_alter_homesliderimage_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='gallery/')),
            ],
        ),
    ]
