# Generated by Django 5.2.5 on 2025-08-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamK', '0004_homepagegallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagegallery',
            name='image1',
            field=models.ImageField(blank=True, default='gallery/default.jpg', null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='homepagegallery',
            name='image2',
            field=models.ImageField(blank=True, default='gallery/default.jpg', null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='homepagegallery',
            name='image3',
            field=models.ImageField(blank=True, default='gallery/default.jpg', null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='homepagegallery',
            name='image4',
            field=models.ImageField(blank=True, default='gallery/default.jpg', null=True, upload_to='gallery/'),
        ),
    ]
