# Generated by Django 5.2.5 on 2025-09-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamK', '0007_alter_homepagegallery_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('mortuary_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
        ),
    ]
