# Generated by Django 5.2.5 on 2025-09-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamK', '0008_servicespage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ambulance', 'Ambulance Services'), ('event', 'Event Services')], max_length=20)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
