# Generated by Django 5.2.5 on 2025-09-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamK', '0009_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
    ]
