# Generated by Django 5.2.5 on 2025-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamK', '0010_sitelogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagegallery',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='homegallery/'),
        ),
        migrations.AlterField(
            model_name='homepagegallery',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='homegallery/'),
        ),
        migrations.AlterField(
            model_name='homepagegallery',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='homegallery/'),
        ),
        migrations.AlterField(
            model_name='homepagegallery',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='homegallery/'),
        ),
    ]
