# Generated by Django 5.2.5 on 2025-09-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamK', '0012_alter_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='homesliderimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
        migrations.AlterField(
            model_name='homesliderimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
        migrations.AlterField(
            model_name='homesliderimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='slider/'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='ambulance_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='mortuary_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='sitelogo',
            name='logo',
            field=models.ImageField(upload_to='logo/'),
        ),
    ]
