# Generated by Django 5.2.5 on 2025-09-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamK', '0013_alter_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagegallery',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='Homegallery/'),
        ),
        migrations.AlterField(
            model_name='homepagegallery',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='Homegallery/'),
        ),
        migrations.AlterField(
            model_name='homepagegallery',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='Homegallery/'),
        ),
        migrations.AlterField(
            model_name='homepagegallery',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='Homegallery/'),
        ),
    ]
